'use client';

import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import z from 'zod';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Loader2, CheckCircle2, XCircle, Store } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { checkStoreSlug, createStore } from '@/lib/api/stores';
import { useBootstrapStore } from '@/stores/bootstrapStore';
import { queryKeys } from '@/lib/queryKeys';
import type { ApiError } from '@/types/api';
import { toast } from 'sonner';
import {
  clearCreateStoreDraft,
  loadCreateStoreDraft,
  persistCreateStoreDraft,
} from '@/lib/auth/storage';
import { useDebounce } from '@/lib/hooks/useDebounce';
import { useTranslations } from 'next-intl';

interface Props {
  /** Called after store creation succeeds and provisioning state is set. */
  onSuccess: () => void;
  /** When true, renders as a standalone full-page view (for /setup flow). When false, embeds cleanly inside a dashboard page. */
  fullPage?: boolean;
}

export function CreateStoreStep({ onSuccess, fullPage = true }: Props) {
  const queryClient = useQueryClient();
  const fetchBootstrap = useBootstrapStore((state) => state.fetchBootstrap);
  const setProvisioning = useBootstrapStore((state) => state.setProvisioning);
  const [formError, setFormError] = useState<string | null>(null);
  const [draftRestored, setDraftRestored] = useState(false);
  const [isSlugUserEdited, setIsSlugUserEdited] = useState(false);
  const lastAutoGeneratedSlugRef = useRef('');
  const isSlugUserEditedRef = useRef(false);
  const hasAttemptedDraftRestoreRef = useRef(false);
  const t = useTranslations('setup.createStore');

  const schema = z.object({
    name: z.string().min(3, t('storeNameMin')),
    slug: z
      .string()
      .min(3, t('storeSlugMin'))
      .regex(/^[a-z0-9-]+$/, t('storeSlugRegex')),
  });

  type CreateStoreForm = z.infer<typeof schema>;

  const {
    register,
    control,
    setValue,
    setError,
    handleSubmit,
    formState: { errors, isValid, isSubmitting },
  } = useForm<CreateStoreForm>({
    resolver: zodResolver(schema),
    mode: 'onChange',
    defaultValues: { name: '', slug: '' },
  });

  function generateStoreSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  const name = useWatch({ control, name: 'name' }) ?? '';
  const slug = useWatch({ control, name: 'slug' }) ?? '';
  const slugField = register('slug');
  const debouncedSlug = useDebounce(slug, 500);
  const canCheckSlug = debouncedSlug.length >= 3 && /^[a-z0-9-]+$/.test(debouncedSlug);

  const setSlugUserEditedMode = (value: boolean) => {
    isSlugUserEditedRef.current = value;
    setIsSlugUserEdited(value);
  };

  const handleSlugChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (!isSlugUserEditedRef.current) {
      setSlugUserEditedMode(true);
    }

    slugField.onChange(event);
  };

  const handleResetSlug = () => {
    const generated = generateStoreSlug(name);
    setSlugUserEditedMode(false);
    lastAutoGeneratedSlugRef.current = generated;
    setValue('slug', generated, { shouldValidate: true });
  };

  const slugQuery = useQuery({
    queryKey: ['store-slug-check', debouncedSlug],
    queryFn: ({ signal }) => checkStoreSlug(debouncedSlug, { signal }),
    enabled: canCheckSlug,
    retry: false,
    staleTime: 0,
  });

  const isCheckingSlug = slugQuery.isFetching;
  const slugStatus: 'idle' | 'available' | 'taken' | 'error' = !canCheckSlug
    ? 'idle'
    : slugQuery.isError
      ? 'error'
      : slugQuery.data?.data.available
        ? 'available'
        : slugQuery.data
          ? 'taken'
          : 'idle';

  // Auto-generate slug from name while the field remains in auto mode.
  useEffect(() => {
    if (isSlugUserEditedRef.current) return;

    const generated = generateStoreSlug(name);
    const slugIsAutoManaged = slug.length === 0 || slug === lastAutoGeneratedSlugRef.current;

    if (!generated || !slugIsAutoManaged) return;

    lastAutoGeneratedSlugRef.current = generated;
    if (slug !== generated) {
      setValue('slug', generated, { shouldValidate: true });
    }
  }, [name, setValue, slug]);

  // Restore draft on mount (only when both fields are empty)
  useEffect(() => {
    if (hasAttemptedDraftRestoreRef.current) return;
    if (name || slug) return;

    hasAttemptedDraftRestoreRef.current = true;
    const draft = loadCreateStoreDraft();
    if (!draft || (!draft.name && !draft.slug)) return;
    const generatedDraftSlug = generateStoreSlug(draft.name);
    const restoredSlug = draft.slug;
    const isCustomSlug = restoredSlug !== generatedDraftSlug;

    setSlugUserEditedMode(isCustomSlug);
    lastAutoGeneratedSlugRef.current = generatedDraftSlug;
    setValue('name', draft.name, { shouldDirty: false, shouldValidate: true });
    setValue('slug', restoredSlug, { shouldDirty: false, shouldValidate: true });
    setDraftRestored(true);
  }, [name, setValue, slug]);

  // Persist draft on every change
  useEffect(() => {
    persistCreateStoreDraft({ name, slug });
  }, [name, slug]);

  const onSubmit = handleSubmit(async (data) => {
    setFormError(null);
    try {
      const response = await createStore(data);
      clearCreateStoreDraft();

      // Set provisioning state FIRST so SetupOrchestrator immediately renders
      // ProvisioningStep. Do NOT call fetchBootstrap here — the bootstrap
      // refresh could return before or after the job runs and would either
      // wipe provisioning state or show a completed store prematurely.
      // ProvisioningStep's polling loop owns the lifecycle from here.
      setProvisioning({
        tracked_store_id: response.data.id,
        tracked_store_slug: response.data.slug,
        status: 'pending',
        progress: 0,
        current_step: 'initializing_store',
        message: response.message,
        retryable: false,
        started_at: Date.now(),
        last_checked_at: null,
        soft_timed_out: false,
        hard_timed_out: false,
      });

      toast.success(response.message || t('storeCreationHasStarted'));
      onSuccess();
    } catch (error) {
      const apiError = error as ApiError;

      if (apiError.errors.name?.[0]) {
        setError('name', { message: apiError.errors.name[0] });
      }
      if (apiError.errors.slug?.[0]) {
        setError('slug', { message: apiError.errors.slug[0] });
      }

      const storeError = apiError.errors.store?.[0];
      if (storeError) {
        await queryClient.fetchQuery({
          queryKey: queryKeys.merchant.me(),
          queryFn: ({ signal }) => fetchBootstrap({ signal }),
        });
        clearCreateStoreDraft();
        setFormError(storeError);
        toast.error(storeError);
        onSuccess(); // bootstrap will route to provisioning
        return;
      }

      if (apiError.status === 403) {
        await queryClient.invalidateQueries({ queryKey: queryKeys.merchant.me() });
        setFormError(
          apiError.message || t('storeCreationTemporarilyUnavailablePleaseTryAgainMoment')
        );
        toast.error(apiError.message || t('storeCreationTemporarilyUnavailable'));
        onSuccess();
        return;
      }

      setFormError(
        apiError.message ||
          t('weWerenAbleCreateStoreRightNowPleaseCheckDetailsTryAgain')
      );
      toast.error(apiError.message || t('unableCreateStorePleaseTryAgain'));
    }
  });

  return (
    <div className={fullPage ? "flex min-h-screen items-center justify-center bg-muted/30 p-6" : "flex items-center justify-center p-0"}>
      <div className="mx-auto w-full max-w-lg space-y-8">
        {/* Step indicator */}
        <div className="flex items-center justify-center gap-3">
          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-xs font-medium text-primary">
            <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
          </span>
          <span className="h-px w-6 bg-primary" />
          <span className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
            <span>2</span>
            <span className="hidden sm:inline">{t('stepIndicator')}</span>
          </span>
          <span className="h-px w-6 bg-border" />
          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-muted-bg text-xs font-medium text-muted-foreground">
            3
          </span>
        </div>

        {/* Header */}
        <div className="space-y-2 text-center">
          <div className="flex justify-center">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/10">
              <Store className="h-7 w-7 text-primary" />
            </div>
          </div>
          <h1 className="text-2xl font-bold">{t('title')}</h1>
          <p className="text-muted-foreground">
            {t('description')}
          </p>
        </div>

        {/* Form card */}
        <div className="rounded-xl border bg-card p-6 shadow-sm">
          <form onSubmit={onSubmit} className="space-y-5">
            {formError ? (
              <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
                {formError}
              </div>
            ) : null}

            {draftRestored ? (
              <div className="rounded-lg border border-border/70 bg-muted/40 px-3 py-2 text-sm text-muted-foreground">
                {t('draftRestored')}
              </div>
            ) : null}

            <div className="space-y-2">
              <Label htmlFor="store-name">{t('storeName')}</Label>
              <Input
                id="store-name"
                placeholder={t('storeNamePlaceholder')}
                data-testid="create-store-name"
                disabled={isSubmitting}
                {...register('name')}
              />
              {errors.name ? (
                <p className="text-sm text-destructive">{errors.name.message}</p>
              ) : null}
            </div>

            <div className="space-y-2">
              <Label htmlFor="store-slug">{t('storeSlug')}</Label>
              <div className="relative">
                <Input
                  id="store-slug"
                  placeholder={t('storeSlugPlaceholder')}
                  data-testid="create-store-slug"
                  disabled={isSubmitting}
                  className="pr-10"
                  {...slugField}
                  onChange={handleSlugChange}
                />
                <div className="absolute inset-y-0 right-0 flex items-center pr-3">
                  {isCheckingSlug ? (
                    <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                  ) : null}
                  {!isCheckingSlug && slugStatus === 'available' ? (
                    <CheckCircle2 className="h-4 w-4 text-success" />
                  ) : null}
                  {!isCheckingSlug && slugStatus === 'taken' ? (
                    <XCircle className="h-4 w-4 text-destructive" />
                  ) : null}
                </div>
              </div>
              {errors.slug ? (
                <p className="text-sm text-destructive">{errors.slug.message}</p>
              ) : null}
              {!errors.slug && slugStatus === 'taken' ? (
                <p className="text-sm text-destructive">{t('slugTaken')}</p>
              ) : null}
              {!errors.slug && slugStatus === 'available' ? (
                <p className="text-sm text-success">{t('slugAvailable')}</p>
              ) : null}
              {slugStatus === 'error' ? (
                <p className="text-sm text-muted-foreground">
                  {t('slugError')}
                </p>
              ) : null}
              {isSlugUserEdited && slug.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  {t('slugEmpty')}
                </p>
              ) : null}
              <p className="text-xs text-muted-foreground">
                {t('slugHint')}
              </p>
              {isSlugUserEdited ? (
                <button
                  type="button"
                  className="text-xs font-medium text-primary hover:underline"
                  onClick={handleResetSlug}
                >
                  {t('resetToAuto')}
                </button>
              ) : null}
            </div>

            <Button
              type="submit"
              className="w-full"
              data-testid="create-store-submit"
              disabled={!isValid || isSubmitting || isCheckingSlug || slugStatus === 'taken'}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  {t('creatingStore')}
                </>
              ) : (
                t('createStore')
              )}
            </Button>

            <p className="text-xs text-muted-foreground">
              {t('yourStoreCreationWillContinueBackgroundIfSomethingInterruptsFlowSimplyRefreshPageContinue')}
            </p>
          </form>
        </div>
      </div>
    </div>
  );
}
